server {
    listen 80;
    server_name _;
    root /var/www/public;
    index index.php;
    resolver 127.0.0.11 ipv6=off valid=10s;

    client_max_body_size 64m;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        set $api_fpm api-servicios:9000;
        fastcgi_pass $api_fpm;
        fastcgi_read_timeout 120;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
